// Source:
// Countries with long/lat => https://developers.google.com/public-data/docs/canonical/countries_csv
// Countries images => https://github.com/djaiss/mapsicon

const countryCodesWithImage = [
  "a",
  "ab",
  "al",
  "av",
  "b",
  "ba",
  "bi",
  "bu",
  "c",
  "ca",
  "cc",
  "ce",
  "co",
  "cr",
  "cs",
  "cu",
  "gc",
  "gi",
  "gr",
  "gu",
  "h",
  "hu",
  "ib",
  "j",
  "l",
  "le",
  "lo",
  "lu",
  "m",
  "ma",
  "ml",
  "mu",
  "na",
  "o",
  "ou",
  "p",
  "po",
  "s",
  "sa",
  "se",
  "sg",
  "so",
  "ss",
  "t",
  "te",
  "tf",
  "to",
  "v",
  "va",
  "vi",
  "z",
  "za",
];

export interface Country {
  code: string;
  latitude: number;
  longitude: number;
  name: string;
}

export const countries: Country[] = [
  { code: "AD", latitude: 42.546245, longitude: 1.601554, name: "Andorra" },
  { code: "A", latitude: 38.4786378049, longitude: -0.568699068376, name: "Alicante" },
  { code: "AB", latitude: 38.8254086192, longitude: -1.98037326935, name: "Albacete" },
  { code: "AL", latitude: 37.1960852121, longitude: -2.3448128003, name: "Almeria" },
  { code: "AV", latitude: 40.5710367492, longitude: -4.94553505619, name: "Avila" },
  { code: "B", latitude: 41.7310008895, longitude: 1.98405401772, name: "Barcelona" },
  { code: "BA", latitude: 38.7097707381, longitude: -6.14158521981, name: "Badajoz" },
  { code: "BI", latitude: 43.2376797057, longitude: 2.85260007926, name: "Vizcaya" },
  { code: "BU", latitude: 42.3687127267, longitude: 3.58574245567, name: "Burgos" },
  { code: "C", latitude: 43.1257958229, longitude: -8.4642836868, name: "Coruña" },
  { code: "CA", latitude: 36.5538729195, longitude: 5.7604183752, name: "Cadiz" },
  { code: "CC", latitude: , longitude: , name: "Caceres" },
  { code: "CE", latitude: , longitude: , name: "Ceuta" },
  { code: "CO", latitude: , longitude: , name: "Cordoba" },
  { code: "CR", latitude: , longitude: , name: "Ciudad Real" },
  { code: "CS", latitude: , longitude: , name: "Castellon" },
  { code: "CU", latitude: , longitude: , name: "Cuenca" },
  { code: "GC", latitude: , longitude: , name: "Gran Canaria" },
  { code: "GI", latitude: , longitude: , name: "Girona" },
  { code: "GR", latitude: , longitude: , name: "Granada" },
  { code: "GU", latitude: , longitude: , name: "Guadalajara" },
  { code: "H", latitude: , longitude: , name: "Huelva" },
  { code: "HU", latitude: 42.2030557371, longitude: -0.0728865943582, name: "Huesca" },
  { code: "IB", latitude: , longitude: , name: "Baleares" },
  { code: "J", latitude: 38.0165122783, longitude: -3.44169215171, name: "Jaen" },
  { code: "L", latitude: , longitude: , name: "Lerida" },
  { code: "LE", latitude: , longitude: , name: "Leon" },
  { code: "LO", latitude: , longitude: , name: "La Rioja" },
  { code: "LU", latitude: , longitude: , name: "Lugo" },
  { code: "M", latitude: , longitude: , name: "Madrid" },
  { code: "MA", latitude: , longitude: , name: "Malaga" },
  { code: "ML", latitude: , longitude: , name: "Melilla" },
  { code: "MU", latitude: , longitude: , name: "Murcia" },
  { code: "NA", latitude: , longitude: , name: "Navarra" },
  { code: "O", latitude: , longitude: , name: "Asturias" },
  { code: "OU", latitude: , longitude: , name: "Ourense" },
  { code: "P", latitude: , longitude: , name: "Palencia" },
  { code: "PO", latitude: , longitude: , name: "Pontevedra" },
  { code: "S", latitude: , longitude: , name: "Cantabria" },
  { code: "SA", latitude: , longitude: , name: "Salamanca" },
  { code: "SE", latitude: , longitude: , name: "Sevilla" },
  { code: "SG", latitude: , longitude: , name: "Segovia" },
  { code: "SO", latitude: , longitude: , name: "Soria" },
  { code: "SS", latitude: , longitude: , name: "Gipuzcoa" },
  { code: "T", latitude: , longitude: , name: "Tarragona" },
  { code: "TE", latitude: , longitude: , name: "Teruel" },
  { code: "TF", latitude: , longitude: , name: "Tenerife" },
  { code: "TO", latitude: , longitude: , name: "Toledo" },
  { code: "V", latitude: , longitude: , name: "Valencia" },
  { code: "VA", latitude: , longitude: , name: "Valladolid" },
  { code: "VI", latitude: , longitude: , name: "Alava" },
  { code: "Z", latitude: , longitude: , name: "Zaragoza" },
  { code: "ZA", latitude: , longitude: , name: "Zamora" },
];

export const countriesWithImage = countries.filter((c) =>
  countryCodesWithImage.includes(c.code.toLowerCase())
);

// Source: https://fr.wikipedia.org/wiki/ISO_3166
const frenchCountryNames: Record<string, string> = {
  AF: "Afghanistan",
  AX: "Åland",
  AL: "Albanie",
  DZ: "Algérie",
  AS: "Samoa américaines",
  AD: "Andorre",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctique",
  AG: "Antigua-et-Barbuda",
  AR: "Argentine",
  AM: "Arménie",
  AW: "Aruba",
  AU: "Australie",
  AT: "Autriche",
  AZ: "Azerbaïdjan",
  BS: "Bahamas",
  BH: "Bahreïn",
  BD: "Bangladesh",
  BB: "Barbade",
  BY: "Bélarus",
  BE: "Belgique",
  BZ: "Belize",
  BJ: "Bénin",
  BM: "Bermudes",
  BT: "Bhoutan",
  BO: "Bolivie",
  BQ: "Bonaire, Saint-Eustache et Saba",
  BA: "Bosnie-Herzégovine",
  BW: "Botswana",
  BV: "Bouvet",
  BR: "Brésil",
  IO: "Indien",
  BN: "Brunéi Darussalam",
  BG: "Bulgarie",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  KH: "Cambodge",
  CM: "Cameroun",
  CA: "Canada",
  KY: "Caïmans",
  CF: "République centrafricaine",
  TD: "Tchad",
  CL: "Chili",
  CN: "Chine",
  CX: "Christmas",
  CC: "Cocos",
  CO: "Colombie",
  KM: "Comores",
  CD: "République démocratique du Congo",
  CG: "Congo",
  CK: "Cook",
  CR: "Costa Rica",
  HR: "Croatie",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Chypre",
  CZ: "Tchéquie",
  DK: "Danemark",
  DJ: "Djibouti",
  DM: "Dominique",
  DO: "République dominicaine",
  EC: "Équateur",
  EG: "Égypte",
  SV: "Salvador",
  GQ: "Guinée équatoriale",
  ER: "Érythrée",
  EE: "Estonie",
  SZ: "Eswatini",
  ET: "Éthiopie",
  FK: "Îles Falkland (Malvinas)",
  FO: "Féroé",
  FJ: "Fidji",
  FI: "Finlande",
  FR: "France",
  GF: "Guyane française",
  PF: "Polynésie française",
  TF: "Terres australes françaises",
  GA: "Gabon",
  GM: "Gambie",
  GE: "Géorgie",
  DE: "Allemagne",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Grèce",
  GL: "Groenland",
  GD: "Grenade",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernesey",
  GN: "Guinée",
  GW: "Guinée-Bissau",
  GY: "Guyana",
  HT: "Haïti",
  HM: "Heard-et-Îles MacDonald",
  VA: "Saint-Siège",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hongrie",
  IS: "Islande",
  IN: "Inde",
  ID: "Indonésie",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Irlande",
  IM: "Île de Man",
  IL: "Israël",
  IT: "Italie",
  CI: "Côte d'Ivoire",
  JM: "Jamaïque",
  JP: "Japon",
  JE: "Jersey",
  JO: "Jordanie",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "Corée du Nord",
  KR: "Corée du Sud",
  KW: "Koweït",
  KG: "Kirghizistan",
  LA: "Lao",
  LV: "Lettonie",
  LB: "Liban",
  LS: "Lesotho",
  LR: "Libéria",
  LY: "Libye",
  LI: "Liechtenstein",
  LT: "Lituanie",
  LU: "Luxembourg",
  MO: "Macao",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaisie",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malte",
  MH: "Marshall",
  MQ: "Martinique",
  MR: "Mauritanie",
  MU: "Maurice",
  YT: "Mayotte",
  MX: "Mexique",
  FM: "Micronésie",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolie",
  ME: "Monténégro",
  MS: "Montserrat",
  MA: "Maroc",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibie",
  NR: "Nauru",
  NP: "Népal",
  NL: "Pays-Bas",
  NC: "Nouvelle-Calédonie",
  NZ: "Nouvelle-Zélande",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigéria",
  NU: "Niue",
  NF: "Norfolk",
  MK: "Macédoine du Nord",
  MP: "Mariannes du Nord",
  NO: "Norvège",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palaos",
  PS: "Palestine",
  PA: "Panama",
  PG: "Papouasie-Nouvelle-Guinée",
  PY: "Paraguay",
  PE: "Pérou",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Pologne",
  PT: "Portugal",
  PR: "Porto Rico",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Roumanie",
  RU: "Russie",
  RW: "Rwanda",
  BL: "Saint-Barthélemy",
  SH: "Sainte-Hélène, Ascension et Tristan da Cunha",
  KN: "Saint-Kitts-et-Nevis",
  LC: "Sainte-Lucie",
  MF: "Saint-Martin",
  PM: "Saint-Pierre-et-Miquelon",
  VC: "Saint-Vincent-et-les Grenadines",
  WS: "Samoa",
  SM: "Saint-Marin",
  ST: "Sao Tomé-et-Principe",
  SA: "Arabie saoudite",
  SN: "Sénégal",
  RS: "Serbie",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapour",
  SX: "Saint-Martin",
  SK: "Slovaquie",
  SI: "Slovénie",
  SB: "Salomon",
  SO: "Somalie",
  ZA: "Afrique du Sud",
  GS: "Géorgie du Sud-et-les Îles Sandwich du Sud",
  SS: "Soudan du Sud",
  ES: "Espagne",
  LK: "Sri Lanka",
  SD: "Soudan",
  SR: "Suriname",
  SJ: "Svalbard et l'Île Jan Mayen",
  SE: "Suède",
  CH: "Suisse",
  SY: "Syrie",
  TW: "Taïwan",
  TJ: "Tadjikistan",
  TZ: "Tanzanie",
  TH: "Thaïlande",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinité-et-Tobago",
  TN: "Tunisie",
  TR: "Turquie",
  TM: "Turkménistan",
  TC: "Turks-et-Caïcos",
  TV: "Tuvalu",
  UG: "Ouganda",
  UA: "Ukraine",
  AE: "Émirats arabes unis",
  GB: "Royaume-Uni",
  UM: "Îles mineures éloignées des États-Unis",
  US: "États-Unis d'Amérique",
  UY: "Uruguay",
  UZ: "Ouzbékistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Viet Nam",
  VG: "Vierges britanniques",
  VI: "Vierges des États-Unis",
  WF: "Wallis-et-Futuna",
  EH: "Sahara occidental",
  YE: "Yémen",
  ZM: "Zambie",
  ZW: "Zimbabwe",
  AN: "Antilles néerlandaises",
  GZ: "Bande de Gaza",
  XK: "Kosovo",
};

export function getCountryName(language: string, country: Country) {
  if (language === "fr") {
    return frenchCountryNames[country.code];
  }
  return country.name;
}

export function sanitizeCountryName(countryName: string): string {
  return countryName
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[- '()]/g, "")
    .toLowerCase();
}
